# Generated by Django 5.1.4 on 2024-12-24 22:10

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='نامک')),
                ('status', models.BooleanField(default=False, verbose_name='منتشر شود')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان برچسب')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='نامک')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='نامک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='بنر مقاله')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوای مقاله')),
                ('status', models.BooleanField(default=False, verbose_name='منتشر شود')),
                ('view', models.IntegerField(default=0, editable=False, verbose_name='بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده مقاله')),
                ('category', models.ManyToManyField(related_name='articles', to='blog.category', verbose_name='انتخاب دسته بندی')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='articles', to='blog.tag', verbose_name='انتخاب برچسب')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
