# Generated by Django 5.1.4 on 2024-12-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_author_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='blog.tag', verbose_name='انتخاب برچسب'),
        ),
    ]
