# Generated by Django 4.2.7 on 2024-12-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_subscriber_alter_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'عضو خبرنامه', 'verbose_name_plural': 'اعضای خبرنامه'},
        ),
    ]
